### ISSUE TITLE
No form found on the webpage

### ISSUE THREAD

**Issue by Floockyone** [2kwattz/Instagram-Bruteforcer#1]
Dear Kwattz, that is the output after givin Insta.name: http status 200 and no form found on webpage.

You'll have a solution ?

Best wishes from germany

**Comment by 2kwattz** [comment]
Dear Floockyone

Thank you so much for your feedback. The script is still under development as written in README.md , The progress of the code would depend on my free time too. Although i feel i should have kept the code private until then (my bad). Thank you so much for understanding. I'm a NodeJs developer who is recently switching to python. So considerably not that kinda pro 

Best wishes from India 
Regards
Roshan Bhatia

**Comment by 2kwattz** [comment]
PS: The issue is fixed now and the script is functional. Thanks!
